import React, { useState } from 'react';
import './AiAssistant.css'

function AIAssistant() {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    // In a real app, you would send the query to an AI service and get a response
    const mockResponse = `Here's a mock AI response for your query: "${query}". In a real application, this would be generated by an AI model.`;
    setResponse(mockResponse);
    setQuery('');
  };

  return (
    <div className="ai-assistant">
      <h2>AI Investment Assistant</h2>
      <form onSubmit={handleSubmit}>
        <input
          type="text"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Ask about stocks or investment advice..."
          required
        />
        <button type="submit">Ask AI</button>
      </form>
      {response && (
        <div className="ai-response">
          <h3>AI Response:</h3>
          <p>{response}</p>
        </div>
      )}
    </div>
  );
}

export default AIAssistant;

