import React, { useState } from 'react';

function AIAssistant() {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();

    const mockResponse = `Here's a mock AI response for your query: "${query}". In a real application, this would be generated by an AI model.`;
    setResponse(mockResponse);
    setQuery('');
  };

  return (
    <div className="p-6 max-w-2xl mx-auto bg-secondary rounded-lg shadow-md">
      <h2 className="text-2xl font-bold mb-4 text-text-primary">AI Investment Assistant</h2>
      <form onSubmit={handleSubmit} className="mb-6">
        <div className="flex">
          <input
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Ask about stocks or investment advice..."
            required
            className="flex-grow p-2 border border-gray-600 rounded-l-md bg-primary text-text-primary focus:outline-none focus:ring-2 focus:ring-accent"
          />
          <button 
            type="submit" 
            className="bg-accent hover:bg-accent-dark text-white font-bold py-2 px-4 rounded-r-md"
          >
            Ask AI
          </button>
        </div>
      </form>
      {response && (
        <div className="bg-primary p-4 rounded-md">
          <h3 className="text-lg font-semibold mb-2 text-text-primary">AI Response:</h3>
          <p className="text-text-secondary">{response}</p>
        </div>
      )}
    </div>
  );
}

export default AIAssistant;

